Add Manjaro Linux support

diff --git a/upack b/upack
--- a/upack
+++ b/upack
@@ -33,6 +33,10 @@ centos_dup() {
     yum update
 }
 
+pacman_dup() {
+    pacman -Syu
+}
+
 # $1 - environment name
 up() {
     if [ $1 = debian ]; then
@@ -43,6 +47,9 @@ up() {
         exit 0
     elif [ $1 = centos ]; then
         centos_dup # this is not typo, centos_up === centos_dup
+        exit 0
+    elif [ $1 = pacman ]; then
+        pacman_dup # this is not typo, pacman_up === pacman_dup
         exit 0
     else
         echo "NYI"
@@ -60,6 +67,9 @@ dup() {
         exit 0
     elif [ $1 = centos ]; then
         centos_dup
+        exit 0
+    elif [ $1 = pacman ]; then
+        pacman_dup
         exit 0
     else
         echo "NYI"
@@ -80,6 +90,9 @@ detect_env() {
     grep -q "[Ff]edora" /etc/os-release 2> /dev/null
     if [ $? = 0 ]; then echo fedora; return; fi
 
+    grep -q "manjaro" /etc/os-release 2> /dev/null
+    if [ $? = 0 ]; then echo pacman; return; fi
+
     echo ""
 }
 
@@ -89,6 +102,7 @@ list_supported() {
     echo "Fedora (at least 24)"
     echo "CentOS (at least 7)"
     echo "Dyson (at least Dufay)"
+    echo "Manjaro (at least 17.0)"
 }
 
 en=$(detect_env)
@@ -114,6 +128,13 @@ elif [ $en = redhat ] || [ $en = fedora ] || [ $en = centos ]; then
     map[qmake-qt4]=qt-devel
     map[gnat]=gcc-gnat
     map[wireshark]=wireshark-gtk
+elif [ $en = pacman ]; then
+    map[7z]=p7zip
+    map[7za]=p7zip
+    map[g++]=gcc
+    map[qmake-qt4]=qt4
+    map[gnat]=gcc-ada
+    map[wireshark]=wireshark-gtk
 else
     echo NYI
     exit 1
@@ -126,17 +147,6 @@ if [ $# = 1 ]; then
     if [ $1 = dup ]; then dup $en $1; fi
 fi
 
-if [ $en = debian ]; then
-    cmd=apt-get
-elif [ $en = fedora ]; then
-    cmd=dnf
-elif [ $en = centos ]; then
-    cmd=yum
-else
-    echo "NYI: detect exact version to deside dnf or yum or something"
-    exit 1
-fi
-
 if [ $# -ge 1 ]; then
     if [ $1 != install ] && [ $1 != remove ]; then
         usage;
@@ -145,6 +155,26 @@ if [ $# -ge 1 ]; then
 else
     usage;
     exit 0;
+fi
+
+if [ $en = debian ]; then
+    cmd=apt-get $1
+elif [ $en = fedora ]; then
+    cmd=dnf $1
+elif [ $en = centos ]; then
+    cmd=yum $1
+elif [ $en = pacman ]; then
+    if [ $1 = install ]; then
+        cmd="pacman -S"
+    elif [ $1 = remove ]; then
+        cmd="pacman -Rs"
+    else
+        echo "Internal error"
+        exit 1
+    fi
+else
+    echo "Internal error: add check for a new environment"
+    exit 1
 fi
 
 for i in $@; do
@@ -167,9 +197,14 @@ for i in $UNPROCPKGS; do
     fi
 done
 
-finalCmd="$cmd $1 $PROCESSEDPKGS"
+finalCmd="$cmd $PROCESSEDPKGS"
 if [ $FORCEY = 1 ]; then
-    finalCmd="$finalCmd -y"
+    if [ $en != pacman ]; then
+        finalCmd="$finalCmd -y"
+    else
+        echo "NOTE: pacman doesn't support -y key (yet), ignoring -y"
+        finalCmd="$finalCmd"
+    fi
 fi
 
 if [ $DRYRUN = 1 ]; then
