Add openSUSE uninstall autoremove unused deps

diff --git a/upack b/upack
--- a/upack
+++ b/upack
@@ -285,7 +285,14 @@ elif [ $en = freebsd ]; then
         exit 1
     fi
 elif [ $en = suse ]; then
-    cmd="zypper $1"
+    if [ $1 = install ]; then
+        cmd="zypper $1"
+    elif [ $1 = remove ]; then
+        cmd="zypper $1 -u"
+    else
+        echo "Internal error"
+        exit 1
+    fi
 elif [ $en = solaris ]; then
     if [ $1 = install ]; then
         cmd="pkg install"
